### ISSUE TITLE
daily

### ISSUE THREAD

**Issue by twrocket** [twrocket/summer_project#1]

**Comment by twrocket** [comment]
今天做什麼?
明天要做什麼
遇到的問題

**Comment by twrocket** [comment]
|日期|A|B|C|

**Comment by abc05412** [comment]
<-aa-->

**Comment by twrocket** [comment]
|A|

**Comment by abc05412** [comment]
|a-----|

**Comment by leotang40** [comment]
|    日期    |   許明騏 |   湯健元   |   王咨閔   | 
| --------- | ---------- | ---------- | ---------- |
|8/01|1. 上了密集訓練課程，之後討論了明天的行程<br> 2. 明天將形成跟目標正式安排完 <br>3. 目前沒有 |1. 上課與討論網站架構<br>2. 將網站架構與詳細內容安排完成<br>3. 目前沒有|1.課程和決定目標 <br> 2.複習上課內容<br> 無|
|8/02|1. 討論網頁的細節 <br> 2. 明天開始做初步資料庫連結<br> 3. 目前沒有 |1. 討論網站架構及學習使用模板<br>2. 複習上課內容與繼續學習模板的使用<br>3. 目前沒有|1.討論網站架構 複習內容<br>2.做backlog修正<br>3.git pull和 push 問題|
|8/03|1. 解決.env及vendor資料夾無法push之問題<br> 2. 熟悉資料庫語法<br> 3. 無法確定 gitignore的忽略規則修改後 上傳vendor及env會不會有問題 |1. 解決.env及vendor資料夾所導致網頁無法開啟之問題，以及複習MVC架構與前端布局<br>2. 製作公告網頁<br>3. 目前沒有|1.解決git 上.env vender無法push所造成的問題<br>2.登錄與否的判斷<br>3.session問題|
|8/04| 1. 學習php語法<br>2. 開始學習session用法 <br> 3. 今天沒有 |1. 研究響應式網頁與複習後端資料庫的操作<br>2. 製作公告網頁<br>3. 不會做響應式網頁|1.用session做登錄與否判斷<br>2.連接帳密資料庫<br>3.資料庫三維陣列問題, <br>git pull 遠端分支問題|
|8/05|1. 成功抓取時間 製作部分後端資料庫程式碼<br> 2. 有事情，無進度 <br> 3. git push 出現問題 無法解決 |1. 製作發布貼文頁面<br>2. 有事情，無進度<br>3. 目前沒有|1.做smtp mail的傳輸測試,使用yahoo mail<br>2.繼續測試smtp,連接帳密資料庫<br>3.gmail smtp安全性問題|
|8/06|1. 觀看php語法 與建立migration<br> 2. 待定<br> 3. migration建立失敗 尋找原因中 |1. 製作模板並套用在其他頁面<br>2. 尚未確定<br>3. 目前沒有 |1.測試gmail stmp server,連帳密資料庫<br>2.休息一天<br>3.不知怎麼用驗證碼,研究中|
|8/07|1. 繼續研究資料庫語法<br>2. 待定<br> 3. 無 |1. 大致完成管理者發布公告系統，剩下編輯功能與登入功能尚未完成<br>2. 待定<br>3. 不知如何加入本定時間 |1.有事情,休息一天<br>2.研究驗證碼,以及模板使用<br>3.無|
|8/08|1. 完成網頁點擊比較時間之函式<br>2. 開始寫其他功能<br>3.遇到php需要將變數直傳進javascipt函式 |1. 有事情，休息一天<br>2. 待定<br>3. 目前沒有 |1.研究驗證碼<br>2.資料庫完備，加入名稱與mail<br>3.用src無法呼叫問題|
|8/09|1.修改時間比較函式<br> 2. 寫貼文行程<br> 3. 不懂controller 如何引入javascript 也不太清楚部分功能在控制系統上的定義 |1. 完成編輯功能<br>2. 有事情，休息一天<br>3. 目前沒有|1.研究驗證碼,資料庫完備，加入名稱與mail<br>2.研究認證碼<br>3.img無法跑出來的問題|
|8/10|1. 完成ckeditor功能<br> 2. 完成檔案上傳　功能<br>  3. 無|1. 研究ckeditor與session<br>2. 待定<br>3.目前沒有|1.資料庫增加名稱和mail欄位<br>2.搜尋帳密<br>3.無|
|8/11|1.查詢檔案下載功能<br> 2. 繼續完成檔案上傳功能 <br>3.無 |1. 有事情，暫停一天<br>2. 待定<br>3. 目前沒有|1.查核身分<br>2.研究網頁美編<br>3.副函式使用問題|
|8/12|1. 繼續完成檔案上傳功能<br>2. 繼續完成檔案上傳功能<br>3. 無 |1. 有事情，暫停一天<br>2. 待定<br>3. 目前沒有|1.研究網頁模板<br>2.美化首頁<br>3.無|
|8/13|1. 繼續完成檔案上傳功能<br>2. 繼續完成檔案上傳功能<br>3. 無 |1. 有事情，暫停一天<br>2. 待定<br>3. 目前沒有|1.美化首頁<br>2.美化首頁與管理者權限設置<br>3.無|
|8/14|1. 檔案上傳功能跟確認上架中的狀態<br>2. 待定<br> 3.不確定為何檔案上傳功能無法上傳pdf |1. 研究session的使用<br>2. 製作大學繁星網頁<br>3. 目前沒有|1.幫忙研究session的使用，美化網頁<br>2.忘記密碼功能<br>3.無|
|8/15|1. 增加資料庫狀態列<br>2. 增加四種管理頁面<br>3. php引用不同php之函式之方法|1. 製作大學繁星網頁<br>2. 繼續製作大學繁網頁<br>3. 目前沒有 |1.忘記密碼功能<br>2.忘記密碼功能<br>3.無|
|8/16|1. 完成上架中 未上架 已下架之網頁 <br>2. 增加分頁功能 <br> 3. 無 |1. 製作大學繁星網頁<br>2. 繼續製作大學繁網頁<br>3. 目前沒有 |1.忘記密碼功能<br>2.前端首頁設計<br>3.session使用問題|
|8/17|1.美化前端<br> 2. 美化前端<br> 3. 無 |1. 製作大學繁星網頁<br>2. 繼續製作大學繁網頁<br>3. 目前沒有 |1.前端首頁設計<br>2.前端首頁設計<br>無|
|8/18|1. 美化網頁<br> 2. 有事情，休息一天 <br>3. 無  |1. 大致完成大學繁星網頁<br>2. 待定<br>3. 不會將boostrap模板客製化  |1.首頁前端設計<br>2.首頁前端設計<br>3.無|
|8/19|1. 有事情 休息一天<br> 2. 美化前端 <br> 3. 無 |1. 美化大學繁星網頁<br>2. 研究動態切換頁面<br>3. 目前沒有 |1.美化首頁<br>2.登入頁面美化<br>3.無|
|8/20|1.控制系統控制進入頁面的功能完成<br>2. 學習jQuery <br>3. 無 |1. 研究動態切換頁面<br>2. 研究公告欄分頁及搜尋功能<br>3. 目前沒有 |1.登入頁面美化<br>2.改進controller程式碼<br>3.無|
|8/21|1. 完成搜尋功能<br> 2. 將搜尋功能用在前端上<br>3. 無 |1. 製作公告欄分頁功能<br>2. 研究公告欄分頁及搜尋功能<br>3. 目前沒有 |1.改進controller程式碼<br>2.休息一天<br>3.無|
|8/22|1.完成搜尋功能<br>2. 請假一天<br>3. 無 |1. 完成大學繁星網頁<br>2. 美化管理者公告頁面<br>3. 目前沒有 |1.休息一天<br>2.重設密碼功能<br>3.無|
|8/23|1. 有事情，暫停一天<br>2. 待定<br>3. 目前沒有 |1. 美化管理者公告頁面<br>2. 待定<br>3. 目前沒有 |1.重設密碼<br>2.review程式碼<br>3.無|
|8/24|1. 有事情，暫停一天<br>2. 待定<br>3. 目前沒有 |1. 有事情，暫停一天<br>2. 待定<br>3. 目前沒有|1.review程式碼<br>2.整理story point<br>無|
|8/25|1. 將判斷丟到controller<br>2. 待定<br>3. 目前沒有 |1. 修改管理者公告介面<br>2. 完成大學個申、高中繁星、高中個申網頁<br>3. 目前沒有|1.整理story point<br>2.整理程式碼<br>3.無|
|8/26|1. 有事情，暫停一天<br>2. 待定<br>3. 目前沒有 |1. 完成大學個申、高中繁星、高中個申網頁<br>2. 待定<br>3. 目前沒有|1.整理程式碼<br>2.ppt製作<br>3.無|
|8/27| 1. 有事情，暫停一天<br>2. 待定<br>3. 目前沒有|1. 有事情，暫停一天<br>2. 待定<br>3. 目前沒有|1.ppt製作<br>2.搬宿<br>3.無|
|8/28|1. 完成報告之ptt<br>2. 已完成 <br>3. 目前沒有 |1. 有事情，暫停一天<br>2. 待定<br>3. 目前沒有|1.搬宿<br>2.搬宿<br>3.無|
|8/29|1. 有事情，暫停一天<br>2. 待定<br>3. 目前沒有 |1. 有事情，暫停一天<br>2. 確定最後版本<br>3. 目前沒有|1.搬宿<br>2.確定最後版本<br>3.無|
|8/30|1. 確定最後版本<br>2. 已完成<br>3. 目前沒有 |1. 確定最後版本<br>2. 已完成<br>3. 目前沒有|1. 確定最後版本<br>2. 最後衝刺<br>3. 目前沒有|
|8/31|1. 已完成<br>2. 已完成<br>3. 目前沒有 |1. 最後衝刺<br>2. 報告<br>3. 目前沒有|1. 最後衝刺<br>2. 報告<br>3. 目前沒有|

**Comment by abc05412** [comment]
|    日期    |   A   |   B   |   C   |   D   |
| --------- | ---------- | ---------- | ---------- | ---------- |

**Comment by twrocket** [comment]
| A | B |
|---|---|
